# preload = ~/.config/backgrounds/shaded.png
# wallpaper = , ~/.config/backgrounds/shaded.png

wallpaper {
    monitor = 
    path = ~/Downloads/photo-1504625709867-b4e45e3bb9dd.jpeg
    fit_mode = cover
}
